/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package travelmaestro;

/**
 *
 * @author Asus
 */
public class exp extends javax.swing.JFrame {

    /**
     * 
     * Creates new form exp
     */
    public exp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        glow1 = new pkgnew.glow();
        glow3 = new pkgnew.glow();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        glow2 = new pkgnew.glow();
        jLabel4 = new javax.swing.JLabel();
        glow4 = new pkgnew.glow();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(235, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("STLiti", 2, 23)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("<html> <body> &nbsp;&nbsp;&nbsp&nbsp;&nbsp;&nbsp\nWelcome to <i>TravelMaestro</i>, your trusted partner for intercity travel adventures in Bangladesh. <br>We are passionate about exploring this beautiful country, and we're here to make your journey not just memorable but also hassle-free. </body> </html>");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1120, 110));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ABOUT US");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 240, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\scenery-around-grossglockner-high-alpine-road-picjumbo-com.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 250));

        glow1.setBackground(new java.awt.Color(255, 255, 255));
        glow1.setBackgroundLight(new java.awt.Color(255, 255, 255));
        glow1.setBorderSize(1);
        glow1.setGradientColor1(new java.awt.Color(0, 102, 102));
        glow1.setShadowSize(10);

        glow3.setBackground(new java.awt.Color(255, 255, 255));
        glow3.setBackgroundLight(new java.awt.Color(255, 255, 255));
        glow3.setBorderSize(1);
        glow3.setGradientColor1(new java.awt.Color(0, 102, 102));
        glow3.setShadowSize(10);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        glow3.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 234, 86);

        glow1.add(glow3);
        glow3.setBounds(0, 0, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\about2.jpg")); // NOI18N
        glow1.add(jLabel3);
        jLabel3.setBounds(20, 20, 330, 170);

        jPanel1.add(glow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 370, 210));

        glow2.setBackground(new java.awt.Color(255, 255, 255));
        glow2.setBackgroundLight(new java.awt.Color(255, 255, 255));
        glow2.setBorderSize(1);
        glow2.setGradientColor1(new java.awt.Color(0, 102, 102));
        glow2.setShadowSize(10);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\undraw_Social_notifications_re_xcbi.jpg")); // NOI18N
        glow2.add(jLabel4);
        jLabel4.setBounds(40, 20, 320, 180);

        jPanel1.add(glow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(726, 770, 390, 220));

        glow4.setBackground(new java.awt.Color(255, 255, 255));
        glow4.setBackgroundLight(new java.awt.Color(255, 255, 255));
        glow4.setBorderSize(1);
        glow4.setGradientColor1(new java.awt.Color(0, 102, 102));
        glow4.setShadowSize(10);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\about1.jpg")); // NOI18N
        glow4.add(jLabel2);
        jLabel2.setBounds(20, 14, 320, 180);

        jPanel1.add(glow4, new org.netbeans.lib.awtextra.AbsoluteConstraints(766, 269, 360, 210));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel7.setText("Our Mission");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("<html>\n<body>\n<b>=></b>Exceptional Service: We believe every journey should be comfortable and enjoyable. Expect safety, convenience, and top-notch service.<br><br>\n\n<b>=></b>Local Insight: Born and raised in Bangladesh, we know the hidden treasures, scenic routes, and authentic experiences this country offers.<br><br>\n\n<b>=></b>Sustainability: We're dedicated to preserving Bangladesh's natural beauty and supporting local communities through responsible travel practices.<br><br>\n\n</body>\n</html>");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 760, -1));

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel9.setText("Join Us on the Journey");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 770, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("<html>\n<body>\n\n<b>~Experienced Team:</b> Our team consists of travel enthusiasts with years of experience exploring Bangladesh. We know the ins and outs of intercity travel here, and we're excited to share our insights with you.<br><br>\n\n<b>~Customized Travel:</b> We understand that every traveler is unique. Whether you're a solo adventurer, a family on vacation, or a group of friends seeking adventure, we tailor our services to meet your specific needs and preferences.<br><br>\n\n<b>~Reliable Partnerships:</b> We have established strong partnerships with trusted transport providers, accommodations, and local guides to ensure a seamless travel experience.<br><br>\n\n</body>\n</html>");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, 710, 230));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 1, 22)); // NOI18N
        jLabel11.setText("Why Choose Us?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("<html><body>\nFollow us on social media to stay updated with the latest travel tips, local insights, and special offers.<br> Let's explore Bangladesh together!\n</body>\n</html>");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 810, 710, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\icons8-instagram-48.png")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 890, 60, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\icons8-facebook-48.png")); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 890, 50, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\Asus\\Desktop\\icons8-twitter-48.png")); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 890, 50, 60));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        setBounds(0, 0, 1163, 817);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkgnew.glow glow1;
    private pkgnew.glow glow2;
    private pkgnew.glow glow3;
    private pkgnew.glow glow4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
